# Generated by Django 2.0.13 on 2022-03-25 09:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Adınız Soyadınız')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=50, verbose_name='Mail Adresiniz')),
                ('subject', models.CharField(max_length=50, verbose_name='Konu')),
                ('message', models.CharField(max_length=50, verbose_name='Mesajınız')),
            ],
        ),
        migrations.CreateModel(
            name='staticAboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100, verbose_name='Sağ Başlık')),
                ('content', models.CharField(max_length=1300, verbose_name='İçerik')),
            ],
        ),
    ]
