# Generated by Django 2.0.13 on 2022-03-25 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticaboutmodel',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Sağ Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticaboutmodel',
            name='title1',
            field=models.CharField(max_length=100, verbose_name='Sol Başlık'),
        ),
    ]
