# Generated by Django 2.0.13 on 2022-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0002_auto_20220325_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticaboutmodel',
            name='title1',
        ),
        migrations.AddField(
            model_name='staticaboutmodel',
            name='title1_Image',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
    ]
