# Generated by Django 3.1.7 on 2022-03-28 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0003_auto_20220325_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='subFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Mail Adresiniz')),
            ],
        ),
        migrations.AddField(
            model_name='staticaboutmodel',
            name='content2',
            field=models.CharField(default=django.utils.timezone.now, max_length=1300, verbose_name='İçerik2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
