# Generated by Django 3.1.7 on 2022-03-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0004_auto_20220328_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='referans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1_Image', models.ImageField(blank=True, null=True, upload_to='refer')),
            ],
        ),
    ]
