# Generated by Django 3.1.7 on 2022-03-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0006_referans_title2_adres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='referans',
            new_name='referanss',
        ),
    ]
