# Generated by Django 3.1.7 on 2022-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0007_auto_20220330_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='referansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1_Image', models.ImageField(blank=True, null=True, upload_to='refer')),
                ('title2_adres', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='referanss',
        ),
    ]
