# Generated by Django 3.1.7 on 2022-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0009_contactformmodel2_referansi2_staticaboutmodel2_subformmodel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referansi',
            name='title2_adres',
        ),
        migrations.AddField(
            model_name='referansi',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
