# Generated by Django 3.1.7 on 2022-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage1', '0010_auto_20220410_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticaboutmodel2',
            name='title1_Image',
            field=models.ImageField(blank=True, null=True, upload_to='about2'),
        ),
    ]
